<ivy-module version="2.0">
  <info organisation="com.lightstreamer" module="ls-javase-client" revision="${version}"/>
  <configurations>
    <conf name="default" visibility="public"></conf>
  </configurations>
  <publications xmlns:e="urn:ant.apache.org:ivy-extras">
    <artifact type="pom" ext="pom" conf="default"/>
    <artifact type="jar" ext="jar" conf="default"/>
    <artifact type="javadoc" ext="jar" conf="default" e:classifier="javadoc"/>
    <artifact type="source" ext="jar" conf="default" e:classifier="sources"/>
  </publications>
  <dependencies>
      <dependency org="com.google.code.findbugs" name="jsr305" rev="3.0.2" conf="default->default"/>
      <dependency org="com.squareup.okhttp3" name="okhttp" rev="5.3.2" conf="default->default"/>
      <dependency org="com.squareup.okhttp3" name="okhttp-urlconnection" rev="5.3.2" conf="default->default"/>
      <!-- zjsonpatch is compatible with both Jackson 2.x and 3.x but requires explicitly declaring one version -->
      <dependency org="com.fasterxml.jackson.core" name="jackson-databind" rev="2.18.8" conf="default->default"/>
      <dependency org="io.github.vishwakarma" name="zjsonpatch" rev="0.6.2" conf="default->default"/>
  </dependencies>
</ivy-module>